### ISSUE TITLE
Design API

### ISSUE THREAD

**Issue by jtcramer** [marl/openl3#1]
Determine the structure of the API and function signatures

**Comment by jtcramer** [comment]
To start the discussion for the API design here's some initial thoughts. I'll just be focusing on the key things for now.

- openl3/audio/core.py
    - build_and_load_model(input_repr, content_type, embedding_type)
    - get_embedding(audio, sr, input_repr="mel256", content_type="music", embedding_size="large", center=True, hop_size=0.1, verbose=1)
    - process_file(filepath, output=None, input_repr="mel256", content_type="music", embedding_size="large", center=True, hop_size=0.1, verbose=True)
    - get_output_path(filepath, suffix, output_dir)

-openl3/audio/models.py
    - load_embedding(input_repr, content_type, embedding_size)
    - get_embedding_path(input_repr, content_type, embedding_size)
    - _construct_linear_audio_network()
    - _construct_mel128_audio_network()
    - _construct_mel256_audio_network()

input_repr: "linear", "mel128", or "mel256"
content_type: "music" or "env"
embedding_size: "large" or "small"

**Comment by justinsalamon** [comment]
I'm not sure we need to separate different aspects of the model into separate parameters i.e. `input_repr`, `content_type` and `embedding_type` (the latter also is way too ambiguous). 

Since we only have 6 models, I'd consider defining a fixed set of 6 strings to represent each (e.g. based the ones proposed in #4). Each model string identifies it uniquely, and the user need only specify one string to define exactly which model to use (e.g. `openl3_mel128_music`).

For the embedding size, I'm not a fan of "big" and "small" because those are ambiguous, and I would favor being explicit about the dimensions, e.g. 6144 (which could the default) and 512. We can check in the function if the provided value is supported and throw an error if not. This gives us the flexibility to support other (potentially any valid) output dimensionalities.

thoughts?

**Comment by jtcramer** [comment]
That's a fair point. Erring towards simplicity seems like a good idea.

I think I meant `embedding_size` instead of `embedding_type`. But that brings up a question of how we want to deal with different pool sizes in terms of how the models are loaded. Since different pool sizes would result in separate models, then we could either load them separately. Alternatively we could also implement the pooling in numpy so we just have to load one model. But maybe we can shelf this discussion since it doesn't affect the API.

Regarding the embedding size, I like user friendly strings, but it does engineer us into a corner (regarding naming conventions, which as you mentioned are ambiguous/subjective). Overall, I'm fine with making it explicit.

**Comment by jtcramer** [comment]
Yeah, I agree that "big" and "small" aren't user friendly. I was more just talking about descriptive names, if it makes sense. I was taking inspiration from the model names in [crepe](https://github.com/marl/crepe/blob/master/crepe/core.py#L12). But yes, it does impose constraints on adding embedding sizes since we'd have to come up with a naming convention that both is clear, and is amenable to adding an arbitrary number of embedding sizes.

Okay great, let's go with numpy pooling. The additional benefit would be that it could be possible to compute embeddings of different sizes without having to do multiple forward passes through the network.

**Comment by justinsalamon** [comment]
> Okay great, let's go with numpy pooling. The additional benefit would be that it could be possible to compute embeddings of different sizes without having to do multiple forward passes through the network.

👍

**Comment by jtcramer** [comment]
Updated API:

- openl3/audio/core.py
    - build_and_load_model(input_repr, content_type, embedding_size)
    - get_embedding(audio, sr, input_repr="mel256", content_type="music", embedding_size=6144, center=True, hop_size=0.1, verbose=1)
    - process_file(filepath, output=None, input_repr="mel256", content_type="music", embedding_size=6144, center=True, hop_size=0.1, verbose=True)
    - get_output_path(filepath, suffix, output_dir)

- openl3/audio/models.py
    - load_embedding(input_repr, content_type, embedding_size)
    - get_embedding_path(input_repr, content_type, embedding_size)
    - _construct_linear_audio_network()
    - _construct_mel128_audio_network()
    - _construct_mel256_audio_network()

input_repr: "linear", "mel128", or "mel256"
content_type: "music" or "env"
embedding_size: 6144 or 512

Any thoughts or should we proceed with this?

**Comment by justinsalamon** [comment]
What's the purpose of having both `core.build_and_load_model` and `models.load_embedding` ?

Also, we should define the outputs of each function as part of the API definition.

**Comment by jtcramer** [comment]
Ah you're right, we don't need both.

A more detailed outline:

- openl3/audio/core.py
    - get_embedding(audio, sr, input_repr="mel256", content_type="music", embedding_size=6144, center=True, hop_size=0.1, verbose=1)
        - Computes and returns L3 embedding for given audio data
        - Inputs
            - audio: np.ndarray; audio array
            - sr: int; sampling rate, if not 48000, will be resampled
            - input_repr: "linear", "mel128", or "mel256"; spectrogram representation used for model
            - content_type: "music" or "env"; type of content used to train embedding
            - embedding_size: 6144 or 512; embedding dimensionality
            - center: bool; if True, pads beginning of signal so timestamps corresponds to center of window
            - hop_size: float; hop size in seconds
            - verbose: 1 or 0; Keras verbosity
        - Outputs
            - embedding: np.array
            - timestamps: np.array
    - process_file(filepath, output_filepath=None, input_repr="mel256", content_type="music", embedding_size=6144, center=True, hop_size=0.1, verbose=True)
        - Computes and saves L3 embedding for given audio file
        - Inputs
            - filepath: str; path to audio file
            - output_filepath: str or None; path of output embedding, if None saves in same directory using the same file basename
            - input_repr: "linear", "mel128", or "mel256"; spectrogram representation used for model
            - content_type: "music" or "env"; type of content used to train embedding
            - embedding_size: 6144 or 512; embedding dimensionality
            - center: bool; if True, pads beginning of signal so timestamps corresponds to center of window
            - hop_size: float; hop size in seconds
            - verbose: bool; If True, Keras will be verbose
    - get_output_path(filepath, suffix, output_dir)
        - Get output path using the given output directory, the basename of the given file, and appending the given suffix
        - Inputs
            - filepath: str; path to audio file
            - suffix: str; string to append to filename (including extension)
            - output: str; path to directory where file will be saved
        - Outputs
            - output_path: str; path to output file

- openl3/audio/models.py
    - get_embedding_model(input_repr, content_type, embedding_size)
        - Returns a model with the given characteristics. Loads the model if the model has not been loaded yet.
        - Inputs
            - input_repr: "linear", "mel128", or "mel256"; spectrogram representation used for model
            - content_type: "music" or "env"; type of content used to train embedding
            - embedding_size: 6144 or 512; embedding dimensionality
        - Outputs
            - model: keras.models.Model; model object
    - get_embedding_model_path(input_repr, content_type, embedding_size)
        - Returns the local path to the model weights file for the model with the given characteristics
        - Inputs
            - input_repr: "linear", "mel128", or "mel256"; spectrogram representation used for model
            - content_type: "music" or "env"; type of content used to train embedding
            - embedding_size: 6144 or 512; embedding dimensionality
        - Outputs
            - model_path: str; path to embedding model weights

    - _construct_linear_audio_network()
        - Returns an uninitialized model object for a network with a linear spectrogram input (With 257 frequency bins)
        - Outputs:
            - model: keras.models.Model; model object
    - _construct_mel128_audio_network()
        - Returns an uninitialized model object for a network with a Mel spectrogram input (with 128 frequency bins)
        - Outputs:
            - model: keras.models.Model; model object
    - _construct_mel256_audio_network()
        - Returns an uninitialized model object for a network with a Mel spectrogram input (with 256 frequency bins)
        - Outputs:
            - model: keras.models.Model; model object

**Comment by jtcramer** [comment]
Should we have a function in the library for processing a directory or is that unnecessary? We will want that behavior for the CLI (for which I'll propose shortly), so we could just include it in the API. But maybe it's something that would be better just being left to users to implement for their own scripts.

**Comment by justinsalamon** [comment]
> Should we have a function in the library for processing a directory or is that unnecessary? We will want that behavior for the CLI (for which I'll propose shortly), so we could just include it in the API. But maybe it's something that would be better just being left to users to implement for their own scripts.

I don't think we need such a function for the python API (people can easily implement themselves), only for the CLI.

**Comment by justinsalamon** [comment]
The proposed API and CLI look good to me!

**Comment by jtcramer** [comment]
Two points I want to address (which maybe are not as important):

- Should we create output directories for the user if they don't exist? I usually prefer to create directories for users out of convenience, but I'm not sure if there's a general consensus for whether this should be done. I guess out of simplicity, we should just let the user worry about it but I want to get your opinion.
- Should we allow users to recursively process audio files? This could be convenient, but opens up a can of worms regarding how we handle the different use cases. e.g. when recursively processing files but saving to a given output directory, should we replicate the directory structure of the audio directory or should we put all of the files in one directory (and if so what is the naming convention)? It's not super unreasonable but might add some potentially unnecessary complexity.
- Should we allow for a text file of paths for the input? 

Regarding the latter two points, I lean towards not supporting that just because it makes things very slightly more complicated. If people end up really wanting it, it's something we can add in later.

**Comment by justinsalamon** [comment]
> Should we create output directories for the user if they don't exist? I usually prefer to create directories for users out of convenience, but I'm not sure if there's a general consensus for whether this should be done. I guess out of simplicity, we should just let the user worry about it but I want to get your opinion.

I think it's reasonable for us to create the immediate parent directory, and assume the rest of the path exists. That is, if the user specifies an output folder as `/a/b/c`, we can assume `/a/b` exists (and throw an error if it does not), and create `c` if it doesn't exist. Thoughts?

> Should we allow users to recursively process audio files? This could be convenient, but opens up a can of worms regarding how we handle the different use cases. e.g. when recursively processing files but saving to a given output directory, should we replicate the directory structure of the audio directory or should we put all of the files in one directory (and if so what is the naming convention)? It's not super unreasonable but might add some potentially unnecessary complexity.

I don't think we need to support recursive processing. The CLI is provided for basic use only. Anything fancy should be done via the python API, and the user can handle recursion themselves.

> Should we allow for a text file of paths for the input?

I'm assuming this is for the CLI. Again I don't think it's necessary, for the CLI I think we need to support processing a single audio file or all audio files in a folder, anything beyond that people should code up themselves using the python API.

> Regarding the latter two points, I lean towards not supporting that just because it makes things very slightly more complicated. If people end up really wanting it, it's something we can add in later.

Agreed.
