### ISSUE TITLE
Handling short audio

### ISSUE THREAD

**Issue by jtcramer** [marl/openl3#12]
I'm thinking about how to handle these cases with short audio:

- Empty audio array
    - Proposed solution: Throw an error. We shouldn't try to process empty audio forms
- Audio array has less than one second of audio
    - Proposed solution: Pad audio to one second and process as usual. Maybe warn the user?

What are your thoughts?

**Comment by justinsalamon** [comment]
Agreed, but we should definitely raise a warning if we're padding the signal.
