### ISSUE TITLE
Handling silence

### ISSUE THREAD

**Issue by jtcramer** [marl/openl3#13]
There are a few different ways we could handle audio with (true) silence, i.e. all zero samples. We could throw an error, but there could be reasons that people want to process silence. We might want to raise a warning so the user is aware. Or we could just do nothing, which could also be reasonable. What are your thoughts?

**Comment by justinsalamon** [comment]
I don't think we need to do anything special. We could raise a warning if the *entire* input signal is perfectly silent, but otherwise I think we can just process as usual.

**Comment by jtcramer** [comment]
I'm thinking about cases where the entire input signal is all zeros.

**Comment by justinsalamon** [comment]
Yes. I'd raise a warning and process as usual.
