### ISSUE TITLE
why I can't install openl3 now？

### ISSUE THREAD

**Issue by zsmj610** [marl/openl3#20]
whether use pip or git clone github repository. When I use pip ，Then it will hang in this step.
![image](https://user-images.githubusercontent.com/19245461/54326881-0e689980-4643-11e9-9b9f-49a687091bed.png)
When I git clone the repository, so did the same .

**Comment by jtcramer** [comment]
Hello, thanks for your interest. The installation includes downloading model files, which could take some time depending on your internet connection.

**Comment by zsmj610** [comment]
> Hello, thanks for your interest. The installation includes downloading model files, which could take some time depending on your internet connection.

Thanks for reply
