### ISSUE TITLE
About pre-trained model and paper

### ISSUE THREAD

**Issue by bearsroom** [marl/openl3#21]
Hello there, I would like to have more details of pre-trained model used by OpenL3 project:
1. On which dataset the pre-trained model is trained? AudioSet or SoundNet-Flickr dataset or another dataset? And what is the number of examples used?
2. Did you reproduce the results described in the original L^3 Net paper or the latest version AVE-Net (Object that sound, ECCV18)?

Besides, congrats to the authors for paper acceptance, but it seems that the paper is not available yet, could you provide some way to download this paper?

Thank you!

**Comment by justinsalamon** [comment]
Hi, the models were trained on two subsets of AudioSet, one containing primarily music videos and the other containing primarily environmental sounds. The linear models reproduce the results of the original L3-Net paper, while the mel-based models outperform the original (linear) models on downstream environmental sound classification tasks.

The complete details are provided in the paper. We'll be making a pre-print available in the coming weeks, hold tight!

Cheers

**Comment by justinsalamon** [comment]
The paper is now linked on the repo’s README :)
