### ISSUE TITLE
Write setup script

### ISSUE THREAD

**Issue by jtcramer** [marl/openl3#3]
Write installation/setup script

**Comment by justinsalamon** [comment]
cf. https://github.com/marl/crepe/blob/master/setup.py

**Comment by jtcramer** [comment]
This is done for now, but once we get into pushing PyPI we might need to change this.

**Comment by justinsalamon** [comment]
I can make this pypi ready if that sounds good?

**Comment by justinsalamon** [comment]
(unless it already is... haven't checked :)

**Comment by jtcramer** [comment]
That sounds good. I can't say that it's necessarily PyPI ready, but it's at least based off of the Scaper and Crepe setup scripts.

**Comment by justinsalamon** [comment]
OK great - those are both pypi ready so we might be fine out of the box, but I can check once the package is ready for upload
