### ISSUE TITLE
Streaming / real-time usage?

### ISSUE THREAD

**Issue by jonnor** [marl/openl3#36]
For many applications it is desirable to be able to classify a real-time audio stream. Assuming that a delay by 1 analysis window size (1 second) is acceptable. Is this use-case something you aim to support with OpenL3, and maybe have tested? If so it would be great to have an example or documentation for it.

Looking briefly at the API docs and source code, it seems this could be possible by combining.
`model = load_embedding_model(...)` with `get_embeddings(chunk, sr, model=model, ...`), where `chunk` is the just-received 1 second of audio. Any caveats?

Also, any estimates on what the hardware requirements would be to reach real-time performance?

**Comment by justinsalamon** [comment]
In principle this should be possible following the approach you described - load the model (to avoid having it re-loaded all the time) and pass it to get_audio_embeddings (new API about to be merged into master with separate methods for audio and image embeddings).

Regarding H/W: it depends on the desired hop size you plan to use. If you plan to use non-overlapping windows (i.e. just 1 prediction per second) it should be totally doable - I have a real-time demo running a similarly sized CNN (albeit in... wait for it... lasagne!) which runs happily on a macbook pro with CPU processing (no GPU required). With a GPU you'll be laughing. Just have to get the preprocessing right to separate audio buffering, prediction, and UI updates.

Closing this out as this isn't actually an issue, but feel free to re-open if you encounter any specific problems.
