### ISSUE TITLE
Upload models

### ISSUE THREAD

**Issue by jtcramer** [marl/openl3#4]
Create a new branch and upload compressed models to it. Make sure we come up with a reasonable naming convention based on API.

**Comment by justinsalamon** [comment]
let's discuss the naming convention for the models. 

To kick things off, how about:

`openl3_<input>_<data>.h5.bz2`

Which would give:

* openl3_linear_music.h5.bz2
* openl3_linear_env.h5.bz2
* openl3_mel128_music.h5.bz2
* openl3_mel128_env.h5.bz2
* openl3_mel256_music.h5.bz2
* openl3_mel256_env.h5.bz2

?

**Comment by jtcramer** [comment]
Given that we also may want to include the image embedding models, we could either put the models in separate folders (e.g. `audio/` `image/`), add `audio` or `image` to the filename (e.g. `openl3_audio_linear_music.h5.bz2`) or both. I'd argue for at least adding it to the filename just so the model names are unambiguous. Doing both may be redundant, but maybe having separate subdirectories would be clear.

**Comment by justinsalamon** [comment]
I agree we should add it to the filename so that filenames are perfectly unambiguous. Since there are just 12 files in total, I'm not sure there's need to save them to separate folders?

**Comment by jtcramer** [comment]
Let's just put it in one folder then. Adding `audio` and `image` to the filenames should be sufficient.

**Comment by jtcramer** [comment]
It has been done.
