### ISSUE TITLE
Save separate embedding models for audio and video

### ISSUE THREAD

**Issue by jtcramer** [marl/openl3#9]
Currently, we save the full L3 model, but it would probably make more sense to separate the embeddings.

**Comment by justinsalamon** [comment]
Why? What are the benefits?

**Comment by jtcramer** [comment]
The RAM usage should roughly half (since we are only loading one of the subnetworks, and skipping the fusion layers). If we can avoid loading more RAM than is necessary, I think it's worth doing. Also, if we are loading smaller model files, then it should also take less time to load.

Regarding the code, while we do have the code to construct/load the full model, it is more to maintain and more to test. Plus, I think a simpler, leaner codebase is generally a good thing if we can help it.

**Comment by justinsalamon** [comment]
Great, thanks for elaborating. Can you carve out the subnetworks for all 6 models (audio and vision), compress and push to this repo on a new "models" branch? There should 12 files in total, right?

**Comment by jtcramer** [comment]
Will do. Yes, there should be 12 files: (3 - linear, mel128, mel256) * (2 - music, env) * (2 - audio, image).
